"""initial schema

Revision ID: 2082358eabfe
Revises: 
Create Date: 2026-07-02 12:12:16.223997
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2082358eabfe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cadet_rank', sa.String(length=50), nullable=False),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('officer_interest', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unenrollment_reason', sa.Text(), nullable=True),
    sa.Column('unenrollment_date', sa.Date(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadet_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_cadet_status'), ['status'], unique=False)

    op.create_table('external_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('potential_recruit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('current_school', sa.String(length=100), nullable=False),
    sa.Column('school_type', sa.String(length=20), nullable=False),
    sa.Column('high_school_graduation_year', sa.Integer(), nullable=True),
    sa.Column('expected_college_graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('potential_recruit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_potential_recruit_stage'), ['stage'], unique=False)

    op.create_table('recruitment_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.String(length=1000), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('secret_question', sa.String(length=200), nullable=False),
    sa.Column('secret_answer_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes_hash', sa.Text(), nullable=True),
    sa.Column('totp_setup_completed', sa.Boolean(), nullable=False),
    sa.Column('can_enable_2fa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('record_description', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('recruit_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['university_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recruit_id'], ['potential_recruit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_recruit_id'), ['recruit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_status'), ['status'], unique=False)

    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_history_user_id'), ['user_id'], unique=False)

    op.create_table('recruit_stage_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=True),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recruit_id'], ['potential_recruit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruit_stage_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruit_stage_event_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recruit_stage_event_recruit_id'), ['recruit_id'], unique=False)

    op.create_table('recruitment_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attendees_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruitment_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitment_event_event_date'), ['event_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitment_event_event_date'))

    op.drop_table('recruitment_event')
    with op.batch_alter_table('recruit_stage_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruit_stage_event_recruit_id'))
        batch_op.drop_index(batch_op.f('ix_recruit_stage_event_changed_at'))

    op.drop_table('recruit_stage_event')
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_history_user_id'))

    op.drop_table('password_history')
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_status'))
        batch_op.drop_index(batch_op.f('ix_follow_up_recruit_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_due_date'))
        batch_op.drop_index(batch_op.f('ix_follow_up_contact_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_assignee_id'))

    op.drop_table('follow_up')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    op.drop_table('activity_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('university_contact')
    op.drop_table('recruitment_document')
    with op.batch_alter_table('potential_recruit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_potential_recruit_stage'))

    op.drop_table('potential_recruit')
    op.drop_table('external_link')
    with op.batch_alter_table('cadet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadet_status'))
        batch_op.drop_index(batch_op.f('ix_cadet_email'))

    op.drop_table('cadet')
    # ### end Alembic commands ###
